#!/usr/bin/env bash
set -euo pipefail

readonly DEFAULT_ARTIFACT="dist/cdn-nginx-linux-amd64.tar.gz"
readonly TEST_IMAGES=("debian:12-slim" "debian:13-slim")

install_mock_commands() {
  install -d -m 0755 /mock-bin /run/cdn-edge-installer-test

  cat >/mock-bin/systemctl <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
state_dir=/run/cdn-edge-installer-test
command="${1:-}"
service="${*: -1}"
case "$command" in
  is-active)
    [[ -f "$state_dir/$service.active" ]]
    ;;
  is-enabled)
    [[ -f "$state_dir/$service.enabled" ]]
    ;;
  enable)
    touch "$state_dir/$service.enabled"
    ;;
  disable)
    rm -f "$state_dir/$service.enabled"
    ;;
  stop)
    if [[ "$service" == "nginx" || "$service" == "nginx.service" ]]; then
      if [[ -x /opt/cdn-edge/nginx/sbin/nginx && -s /opt/cdn-edge/nginx/run/nginx.pid ]]; then
        /opt/cdn-edge/nginx/sbin/nginx -s quit >/dev/null 2>&1 || true
      fi
    fi
    rm -f "$state_dir/$service.active"
    ;;
  start|restart)
    if [[ "$service" == "nginx" || "$service" == "nginx.service" ]]; then
      /opt/cdn-edge/nginx/sbin/nginx
    else
      if [[ "${MOCK_INSTALL_FAILURE:-}" == "agent" ]]; then
        exit 1
      fi
      install -d -m 0750 /opt/cdn-edge/data
      for name in edge-client.key edge-client.crt edge-ca.crt; do
        printf '%s\n' "$name" >"/opt/cdn-edge/data/$name"
        chmod 0600 "/opt/cdn-edge/data/$name"
      done
    fi
    touch "$state_dir/$service.active"
    ;;
  daemon-reload|reset-failed)
    ;;
  *)
    echo "unexpected systemctl invocation: $*" >&2
    exit 1
    ;;
esac
EOF

  cat >/mock-bin/sysctl <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
while [[ "${1:-}" == "-q" ]]; do shift; done
case "${1:-}" in
  -n)
    case "$2" in
      net.core.default_qdisc) echo fq_codel ;;
      net.ipv4.tcp_congestion_control) echo cubic ;;
      net.ipv4.tcp_mtu_probing) echo 0 ;;
      net.core.rmem_max|net.core.wmem_max) echo 4194304 ;;
      net.ipv4.tcp_rmem) echo '4096 131072 6291456' ;;
      net.ipv4.tcp_wmem) echo '4096 16384 4194304' ;;
      *) exit 1 ;;
    esac
    ;;
  -w|-p|--system) exit 0 ;;
  *) exit 1 ;;
esac
EOF

  printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >/mock-bin/modprobe
  printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >/mock-bin/sleep
  chmod 0755 /mock-bin/systemctl /mock-bin/sysctl /mock-bin/modprobe /mock-bin/sleep
}

debian_nginx_packages_present() {
  (dpkg-query -W -f='${binary:Package}\n' 2>/dev/null || true) |
    awk '$1 ~ /^nginx($|-)/ || $1 ~ /^libnginx-mod-/ { found=1 } END { exit found ? 0 : 1 }'
}

container_test() {
  local scenario="$1" install_log=/tmp/cdn-edge-install.log
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq --no-install-recommends nginx
  printf '%s\n' 'operator configuration must survive rollback' >/etc/nginx/operator-marker.conf
  install_mock_commands
  export PATH="/mock-bin:/usr/sbin:/usr/bin:/sbin:/bin"

  if [[ "$scenario" == "layout1" ]]; then
    install -d -m 0755 /opt/cdn-edge/bin /opt/cdn-edge/config/nginx/fragments/stream-v111-24db564cb146 /opt/cdn-edge/data
    printf '%s\n' '1' >/opt/cdn-edge/.layout-version
    printf '%s\n' 'old edge agent' >/opt/cdn-edge/bin/cdn-edge-agent
    printf '%s\n' 'CONTROL_URL=https://control.example.test' >/opt/cdn-edge/config/edge.env
    cat >/opt/cdn-edge/config/nginx/cdn-platform.conf <<'EOF'
# Generated by cdn-edge-agent. Do not edit.
server {
    listen 80 default_server;
    server_name _;
    location = /__cdn_health { access_log off; add_header Content-Type text/plain; return 200 "ok\n"; }
    location / { return 404; }
}
EOF
    cat >/opt/cdn-edge/config/nginx/cdn-platform-stream.conf <<'EOF'
# Generated by cdn-edge-agent. Do not edit.
include /opt/cdn-edge/config/nginx/fragments/stream-v111-24db564cb146/*.conf;
EOF
    cat >/opt/cdn-edge/config/nginx/fragments/stream-v111-24db564cb146/site-mail.conf <<'EOF'
# CDN stream site fragment mail port 19465 begin
log_format cdn_tcp_json '$remote_addr';
server {
    listen 19465;
    proxy_pass 127.0.0.1:9;
    access_log /var/log/nginx/cdn-platform-tcp-access.log cdn_tcp_json;
    error_log /var/log/nginx/cdn-platform-tcp-error.log warn;
}
# CDN stream site fragment mail port 19465 end
EOF
    for name in edge-client.key edge-client.crt edge-ca.crt; do
      printf '%s\n' "$name" >"/opt/cdn-edge/data/$name"
      chmod 0600 "/opt/cdn-edge/data/$name"
    done
  fi

  printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >/tmp/cdn-edge-agent
  chmod 0755 /tmp/cdn-edge-agent
  local binary_sha agent_service_sha updater_service_sha nginx_bundle_sha nginx_service_sha
  binary_sha=$(sha256sum /tmp/cdn-edge-agent | awk '{print $1}')
  agent_service_sha=$(sha256sum /fixtures/install-edge.service | awk '{print $1}')
  updater_service_sha=$(sha256sum /fixtures/install-edge-updater.service | awk '{print $1}')
  nginx_bundle_sha=$(sha256sum /fixtures/cdn-nginx-linux-amd64.tar.gz | awk '{print $1}')
  nginx_service_sha=$(sha256sum /fixtures/install-edge-nginx.service | awk '{print $1}')

  local -a arguments=(
    /fixtures/install-edge.sh
    --control-url https://control.example.test
    --enrollment-token integration-token
    --binary-file /tmp/cdn-edge-agent
    --binary-sha256 "$binary_sha"
    --service-file /fixtures/install-edge.service
    --service-sha256 "$agent_service_sha"
    --updater-service-file /fixtures/install-edge-updater.service
    --updater-service-sha256 "$updater_service_sha"
    --nginx-bundle-file /fixtures/cdn-nginx-linux-amd64.tar.gz
    --nginx-bundle-sha256 "$nginx_bundle_sha"
    --nginx-service-file /fixtures/install-edge-nginx.service
    --nginx-service-sha256 "$nginx_service_sha"
  )
  local -a bash_options=()
  if [[ "${DEBUG_INSTALLER:-}" == "1" ]]; then bash_options=(-x); fi

  if [[ "$scenario" == "success" || "$scenario" == "layout1" ]]; then
    if ! bash "${bash_options[@]}" "${arguments[@]}" >"$install_log" 2>&1; then
      cat "$install_log" >&2
      return 1
    fi
    if debian_nginx_packages_present; then
      echo "Debian Nginx packages remain installed" >&2
      return 1
    fi
    [[ ! -e /etc/nginx ]]
    [[ "$(cat /opt/cdn-edge/.layout-version)" == "2" ]]
    local expected_nginx_version
    expected_nginx_version=$(tar -xOf /fixtures/cdn-nginx-linux-amd64.tar.gz nginx/VERSION | tr -d '[:space:]')
    [[ "$(cat /opt/cdn-edge/nginx/VERSION)" == "$expected_nginx_version" ]]
    [[ "$(stat -c '%a' /opt/cdn-edge/nginx)" == "755" ]]
    [[ "$(stat -c '%a' /opt/cdn-edge/nginx/lib/lua/5.1/resty/core.lua)" == "644" ]]
    if [[ "$scenario" == "layout1" ]]; then
      local stream_fragment=/opt/cdn-edge/config/nginx/fragments/stream-v111-24db564cb146/site-mail.conf
      grep -Fqx '    access_log /opt/cdn-edge/logs/tcp-access.json cdn_tcp_json;' "$stream_fragment"
      grep -Fqx '    error_log /opt/cdn-edge/logs/tcp-error.log warn;' "$stream_fragment"
      ! grep -RFq '/var/log/nginx' /opt/cdn-edge/config/nginx
    fi
    curl --fail --silent --show-error http://127.0.0.1/__cdn_health >/dev/null
    /opt/cdn-edge/nginx/sbin/nginx -s quit
    return
  fi

  export MOCK_INSTALL_FAILURE=agent
  set +e
  bash "${bash_options[@]}" "${arguments[@]}" >"$install_log" 2>&1
  local status=$?
  set -e
  if ((status == 0)); then
    echo "failure scenario unexpectedly succeeded" >&2
    return 1
  fi
  debian_nginx_packages_present
  grep -Fqx 'operator configuration must survive rollback' /etc/nginx/operator-marker.conf
  [[ ! -e /opt/cdn-edge ]]
}

main() {
  if [[ "${1:-}" == "--container" ]]; then
    [[ $# -eq 2 && ( "$2" == "success" || "$2" == "rollback" || "$2" == "layout1" ) ]] || {
      echo "usage: $0 --container success|rollback|layout1" >&2
      return 2
    }
    container_test "$2"
    return
  fi

  local artifact="${1:-$DEFAULT_ARTIFACT}"
  [[ -f "$artifact" ]] || {
    echo "Nginx artifact not found: $artifact" >&2
    return 2
  }
  command -v docker >/dev/null 2>&1 || {
    echo "docker is required to test Debian Nginx migration" >&2
    return 2
  }
  local repository artifact_path script_path fixture_dir cleanup image scenario
  repository=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
  artifact_path=$(cd -- "$(dirname -- "$artifact")" && pwd)/$(basename -- "$artifact")
  script_path="$repository/scripts/$(basename -- "${BASH_SOURCE[0]}")"
  fixture_dir=$(mktemp -d)
  printf -v cleanup 'rm -rf -- %q' "$fixture_dir"
  trap "$cleanup" EXIT
  install -m 0755 "$script_path" "$fixture_dir/test-edge-installer-debian.sh"
  install -m 0755 "$repository/internal/control/install-edge.sh" "$fixture_dir/install-edge.sh"
  install -m 0644 "$repository/internal/control/install-edge.service" "$fixture_dir/install-edge.service"
  install -m 0644 "$repository/internal/control/install-edge-updater.service" "$fixture_dir/install-edge-updater.service"
  install -m 0644 "$repository/internal/control/install-edge-nginx.service" "$fixture_dir/install-edge-nginx.service"
  install -m 0644 "$artifact_path" "$fixture_dir/cdn-nginx-linux-amd64.tar.gz"
  for image in "${TEST_IMAGES[@]}"; do
    for scenario in success rollback layout1; do
      echo "Testing $scenario migration on $image"
      docker run --rm \
        --mount "type=bind,src=$fixture_dir,dst=/fixtures,readonly" \
        "$image" bash /fixtures/test-edge-installer-debian.sh --container "$scenario"
    done
  done
}

main "$@"
