package nginx

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"simple_cdn/internal/domain"
)

type SiteConfig struct {
	Site domain.Site
}

const (
	DefaultCachePath                          = "/opt/cdn-edge/cache"
	DefaultOriginPoolConfigDirectory          = "/opt/cdn-edge/config/nginx/origin-pools"
	DefaultQUICHostKeyPath                    = "/opt/cdn-edge/config/nginx/quic-host.key"
	DefaultStaticAssetDirectory               = "/opt/cdn-edge/static/objects"
	DefaultCacheMaxBytes                int64 = 1 << 30
	defaultClientKeepaliveRequests            = 1000
	defaultUpstreamConnectTimeout             = "10s"
	defaultUpstreamKeepaliveConnections       = 30
	staticAssetPathPattern                    = `\.(?:css|js|mjs|map|wasm|woff|woff2|ttf|otf|eot|jpg|jpeg|png|apng|gif|webp|avif|svg|ico|bmp|tif|tiff|webmanifest)$`
)

const requestTracingMarker = "# Request tracing v1"

const configTemplate = `# Generated by cdn-edge-agent. Do not edit.
{{.SecurityConfig}}
{{.RateLimitConfig}}
{{if .Sites}}
{{if .CachePaths}}
map $uri $cdn_static_cache_zone { default off; ~*{{.StaticAssetPathPattern}} cdn_cache; }
map "$http_authorization:$http_cookie" $cdn_private_cache_bypass { default 1; ":" 0; }
{{end}}
map $http_upgrade $cdn_is_websocket { default 0; ~*^websocket$ 1; }
map $cdn_is_websocket $cdn_connection_upgrade { default ""; 1 upgrade; }
map $cdn_is_websocket $cdn_upstream_upgrade { default ""; 1 $http_upgrade; }
map $http_accept $cdn_accepts_event_stream { default 0; ~*text/event-stream 1; }
map $http_x_cdn_stream $cdn_forced_stream { default 0; "1" 1; }
map "$request_method:$cdn_is_websocket:$cdn_accepts_event_stream:$cdn_forced_stream" $cdn_auto_stream {
    default 0;
    ~^POST: 1;
    ~^[^:]+:1: 1;
    ~^[^:]+:[01]:1: 1;
    ~^[^:]+:[01]:[01]:1$ 1;
}

{{range .CachePaths}}proxy_cache_path {{.Path}} levels=1:2 keys_zone={{.Zone}}:{{.ZoneSize}} inactive=7d max_size={{.MaxSize}} use_temp_path=off;
{{end}}
# Request tracing v1
log_format cdn_json escape=json '{"request_id":"$request_id","client_request_id":"$http_x_request_id","upstream_request_id":"$upstream_http_x_request_id","timestamp":"$time_iso8601","site_id":"$cdn_site_id","client_ip":"$remote_addr","host":"$host","scheme":"$scheme","protocol":"$server_protocol","method":"$request_method","path":"$uri","status":$status,"request_bytes":$request_length,"bytes":$body_bytes_sent,"duration_seconds":$request_time,"request_completion":"$request_completion","upstream":"$upstream_addr","upstream_status":"$upstream_status","upstream_connect_time":"$upstream_connect_time","upstream_header_time":"$upstream_header_time","upstream_response_time":"$upstream_response_time","upstream_bytes_sent":"$upstream_bytes_sent","upstream_bytes_received":"$upstream_bytes_received","cache_status":"$upstream_cache_status","user_agent":"$http_user_agent","referer":"$http_referer","content_type":"$http_content_type","response_content_type":"$sent_http_content_type","accept":"$http_accept","range":"$http_range"}';
{{if .HTTP3Enabled}}quic_host_key {{.QUICHostKeyPath}};
quic_retry on;
{{end}}
{{end}}

{{if .DefaultHTTP}}server {
    listen 80 default_server;
    server_name _;
{{if or .Sites .LegacySecurityEnabled .RuntimeSecurityEnabled}}	set $cdn_site_id "";
{{end}}
	keepalive_timeout {{.DefaultClientKeepaliveTimeout}};
	keepalive_requests {{.ClientKeepaliveRequests}};
{{if .LegacySecurityEnabled}}    access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
{{end}}
{{if .RuntimeSecurityEnabled}}{{range .RuntimeSecurityLogs}}    access_log /opt/cdn-edge/logs/security.json {{.Format}} if=$cdn_security_match_{{.Index}};
{{end}}
    access_by_lua_block { package.loaded.simple_cdn_security.access() }
{{end}}
{{if .RateLimitBanEnabled}}    set $cdn_rate_limit_ban_policy_id "";
    set $cdn_rate_limit_ban_seconds 0;
    access_log /opt/cdn-edge/logs/security.json cdn_rate_limit_ban_json if=$cdn_rate_limit_ban_policy_id;
{{end}}
    location = /__cdn_health { access_log off; add_header Content-Type text/plain; return 200 "ok\n"; }
{{if or .RuntimeSecurityEnabled .RateLimitEnabled}}    location / {
        access_by_lua_block {
            {{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
            {{end}}{{if $.RateLimitEnabled}}package.loaded.simple_cdn_rate_limit.access()
            {{end}}
        }
        {{if $.RateLimitEnabled}}
        header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
        {{end}}
        content_by_lua_block { return ngx.exit(404) }
    }
{{else}}
    location / { return 404; }
{{end}}
}
{{end}}

{{if .Sites}}
server {
    listen 443 ssl default_server;
{{if .HTTP3Enabled}}    listen 443 quic reuseport default_server;
{{end}}
    ssl_reject_handshake on;
    set $cdn_site_id "";
    keepalive_timeout {{.DefaultClientKeepaliveTimeout}};
    keepalive_requests {{.ClientKeepaliveRequests}};
}
{{end}}

{{if .ManagedOriginPools}}
{{range .OriginPools}}
upstream {{.Name}} {
    include {{.ConfigPath}};
    keepalive {{.KeepaliveConnections}};
    keepalive_timeout 45s;
    keepalive_requests 1000;
    keepalive_time 1h;
}
{{if .HTTP1AliasName}}
upstream {{.HTTP1AliasName}} {
    include {{.ConfigPath}};
}
{{end}}
{{end}}
{{end}}

{{range .Sites}}
# CDN HTTP site fragment {{.ID}} begin
{{if not $.ManagedOriginPools}}
{{if .BackupHostPort}}
upstream origin_{{.ID}}_primary {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{if .PrimaryUsesHTTP2}}
upstream origin_{{.ID}}_primary_http1 {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
}
{{end}}

upstream origin_{{.ID}}_backup {
    server {{.BackupHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{if .BackupUsesHTTP2}}
upstream origin_{{.ID}}_backup_http1 {
    server {{.BackupHostPort}} max_fails=2 fail_timeout=10s;
}
{{end}}
{{else}}
upstream origin_{{.ID}} {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{if .PrimaryUsesHTTP2}}
upstream origin_{{.ID}}_http1 {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
}
{{end}}
{{end}}
{{end}}

server {
    listen 80;
    server_name {{.DomainList}};
	set $cdn_site_id "{{.ID}}";
	keepalive_timeout {{.ClientKeepaliveTimeout}};
	keepalive_requests {{$.ClientKeepaliveRequests}};
    add_header X-Request-ID $request_id always;
    {{if $.LegacySecurityEnabled}}access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
    {{end}}
    {{if $.RuntimeSecurityEnabled}}{{range $.RuntimeSecurityLogs}}access_log /opt/cdn-edge/logs/security.json {{.Format}} if=$cdn_security_match_{{.Index}};
    {{end}}
    access_by_lua_block { package.loaded.simple_cdn_security.access() }
    {{end}}
    {{if $.RateLimitBanEnabled}}set $cdn_rate_limit_ban_policy_id "";
    set $cdn_rate_limit_ban_seconds 0;
    access_log /opt/cdn-edge/logs/security.json cdn_rate_limit_ban_json if=$cdn_rate_limit_ban_policy_id;
    {{end}}
    {{if or $.RuntimeSecurityEnabled $.RateLimitEnabled}}location / {
        access_by_lua_block {
            {{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
            {{end}}{{if $.RateLimitEnabled}}package.loaded.simple_cdn_rate_limit.access()
            {{end}}
        }
        {{if $.RateLimitEnabled}}
        header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
        {{end}}
        content_by_lua_block { return ngx.redirect("https://" .. ngx.var.host .. ngx.var.request_uri, 301) }
    }
    {{else}}
    return 301 https://$host$request_uri;
    {{end}}
}

server {
    listen 443 ssl;
    http2 on;
{{if .HTTP3Enabled}}    listen 443 quic;
    http3 on;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;
{{end}}
    server_name {{.DomainList}};
	set $cdn_site_id "{{.ID}}";
    proxy_hide_header X-Request-ID;
    grpc_hide_header X-Request-ID;
    add_header X-Request-ID $request_id always;
    client_max_body_size {{.ClientMaxBodySizeMB}}m;
    keepalive_timeout {{.ClientKeepaliveTimeout}};
    keepalive_requests {{$.ClientKeepaliveRequests}};
    {{if $.LegacySecurityEnabled}}access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
    {{end}}
    {{if $.RuntimeSecurityEnabled}}{{range $.RuntimeSecurityLogs}}access_log /opt/cdn-edge/logs/security.json {{.Format}} if=$cdn_security_match_{{.Index}};
    {{end}}
    access_by_lua_block { package.loaded.simple_cdn_security.access() }
    {{end}}
    {{if $.RateLimitBanEnabled}}set $cdn_rate_limit_ban_policy_id "";
    set $cdn_rate_limit_ban_seconds 0;
    access_log /opt/cdn-edge/logs/security.json cdn_rate_limit_ban_json if=$cdn_rate_limit_ban_policy_id;
    {{end}}

    ssl_certificate /opt/cdn-edge/config/certs/{{.ID}}.crt;
    ssl_certificate_key /opt/cdn-edge/config/certs/{{.ID}}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TLS:10m;
    ssl_session_timeout 30m;

    access_log /opt/cdn-edge/logs/access.json cdn_json;

    location = /__cdn_health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "{{.HealthBody}}\n";
    }

    {{range .StaticAssets}}
    location = "{{.URLPath}}" {
        {{if or $.RuntimeSecurityEnabled $.RateLimitEnabled}}access_by_lua_block {
            {{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
            {{end}}{{if $.RateLimitEnabled}}package.loaded.simple_cdn_rate_limit.access()
            {{end}}ngx.ctx.cdn_static_asset_allowed = true
        }
        header_filter_by_lua_block {
            {{if $.RateLimitEnabled}}package.loaded.simple_cdn_rate_limit.response()
            {{end}}if ngx.ctx.cdn_static_asset_allowed and ngx.status < 400 then
                ngx.header["Cache-Control"] = "{{.CacheControl}}"
                ngx.header["X-Content-Type-Options"] = "nosniff"
            end
        }
        {{else}}
        add_header Cache-Control "{{.CacheControl}}";
        add_header X-Content-Type-Options nosniff;
        {{end}}
        alias "{{.ObjectPath}}";
        types { }
        default_type "{{.ContentType}}";
        etag on;
        if_modified_since exact;
        limit_except GET HEAD { deny all; }
    }
    {{end}}

    {{if .GRPC}}
    location / {
        {{if $.RateLimitEnabled}}access_by_lua_block {
            {{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
            {{end}}package.loaded.simple_cdn_rate_limit.access()
        }
        header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
        {{end}}
		grpc_pass {{.PrimaryScheme}}://{{.PrimaryUpstreamName}};
        grpc_set_header Host {{.HostHeader}};
        grpc_set_header X-Request-ID $request_id;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        grpc_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        grpc_next_upstream_tries 2;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.PrimaryTLSName}};
        grpc_ssl_verify on;
        grpc_ssl_verify_depth 3;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if .BackupHostPort}}
        grpc_intercept_errors on;
        error_page 500 502 503 504 = @cdn_grpc_backup_{{.ID}};
        {{end}}
    }

    {{if .BackupHostPort}}
    location @cdn_grpc_backup_{{.ID}} {
        internal;
        {{if $.RateLimitEnabled}}header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
        {{end}}
		grpc_pass {{.PrimaryScheme}}://{{.BackupUpstreamName}};
        grpc_set_header Host {{.BackupHostHeader}};
        grpc_set_header X-Request-ID $request_id;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.BackupTLSName}};
        grpc_ssl_verify on;
        grpc_ssl_verify_depth 3;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
    }
    {{end}}
	{{else}}
	proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
	proxy_next_upstream_tries 2;
	proxy_connect_timeout {{$.UpstreamConnectTimeout}};
	{{if .BackupHostPort}}
	recursive_error_pages on;
	{{end}}
	{{if .CacheEnabled}}
	proxy_cache $cdn_static_cache_zone;
	proxy_cache_key "{{.ID}}:{{.CacheGeneration}}:$scheme$host$request_uri";
	proxy_cache_bypass $cdn_private_cache_bypass;
	proxy_no_cache $cdn_private_cache_bypass;
    proxy_cache_methods GET HEAD;
    proxy_cache_valid 200 301 302 10m;
    proxy_cache_valid 404 1m;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 10s;
	proxy_cache_revalidate on;
	proxy_cache_background_update on;
	proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
	{{end}}

	location / {
		{{if .DedicatedWebSocket}}
		error_page 417 = @cdn_websocket_{{.ID}};
		{{end}}
		error_page 418 = @cdn_stream_{{.ID}};
		error_page 419 = @cdn_http_{{.ID}};
		{{if .DedicatedWebSocket}}
		if ($cdn_is_websocket) { return 417; }
		{{end}}
		if ($cdn_auto_stream) { return 418; }
		return 419;
	}

	location @cdn_http_{{.ID}} {
		internal;
		proxy_http_version {{.PrimaryProxyHTTPVersion}};
		{{if $.RateLimitEnabled}}access_by_lua_block {
			{{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
			{{end}}package.loaded.simple_cdn_rate_limit.access()
		}
		header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.PrimaryUpstreamName}};
		proxy_set_header Host {{.HostHeader}};
		proxy_set_header X-Request-ID $request_id;
		proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .AlwaysUnbuffered}}
		proxy_cache off;
		{{end}}
		{{if not .OriginResponseBuffering}}
		proxy_buffering off;
		{{end}}
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.PrimaryTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        proxy_ssl_session_reuse on;
        {{end}}
        {{if .BackupHostPort}}
        proxy_intercept_errors on;
		error_page 500 502 503 504 = @cdn_backup_{{.ID}};
		{{end}}
	}

	location @cdn_stream_{{.ID}} {
		internal;
		proxy_http_version {{.PrimaryProxyHTTPVersion}};
		{{if $.RateLimitEnabled}}access_by_lua_block {
			{{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
			{{end}}package.loaded.simple_cdn_rate_limit.access()
		}
		header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.PrimaryUpstreamName}};
		proxy_set_header Host {{.HostHeader}};
		proxy_set_header X-Request-ID $request_id;
		{{if .DedicatedWebSocket}}proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		{{else}}proxy_set_header Upgrade $cdn_upstream_upgrade;
		proxy_set_header Connection $cdn_connection_upgrade;
		{{end}}
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		{{end}}
		{{if .UseTLS}}
		proxy_ssl_server_name on;
		proxy_ssl_name {{.PrimaryTLSName}};
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 3;
		proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		proxy_ssl_session_reuse on;
		{{end}}
		{{if .BackupHostPort}}
		proxy_intercept_errors on;
		error_page 500 502 503 504 = @cdn_stream_backup_{{.ID}};
		{{end}}
	}

	{{if .DedicatedWebSocket}}
	location @cdn_websocket_{{.ID}} {
		internal;
		proxy_http_version 1.1;
		{{if $.RateLimitEnabled}}access_by_lua_block {
			{{if $.RuntimeSecurityEnabled}}package.loaded.simple_cdn_security.access()
			{{end}}package.loaded.simple_cdn_rate_limit.access()
		}
		header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.PrimaryWebSocketUpstreamName}};
		proxy_set_header Host {{.HostHeader}};
		proxy_set_header X-Request-ID $request_id;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection upgrade;
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .UseTLS}}
		proxy_ssl_server_name on;
		proxy_ssl_name {{.PrimaryTLSName}};
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 3;
		proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		proxy_ssl_session_reuse on;
		{{end}}
		{{if .BackupHostPort}}
		proxy_intercept_errors on;
		error_page 500 502 503 504 = @cdn_websocket_backup_{{.ID}};
		{{end}}
	}
	{{end}}

	{{if .BackupHostPort}}
	location @cdn_backup_{{.ID}} {
		internal;
		proxy_http_version {{.BackupProxyHTTPVersion}};
		{{if $.RateLimitEnabled}}header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.BackupUpstreamName}};
		proxy_set_header Host {{.BackupHostHeader}};
		proxy_set_header X-Request-ID $request_id;
		proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .AlwaysUnbuffered}}
		proxy_cache off;
		{{end}}
		{{if not .OriginResponseBuffering}}
		proxy_buffering off;
		{{end}}
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		proxy_ssl_session_reuse on;
		{{end}}
	}

	location @cdn_stream_backup_{{.ID}} {
		internal;
		proxy_http_version {{.BackupProxyHTTPVersion}};
		{{if $.RateLimitEnabled}}header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.BackupUpstreamName}};
		proxy_set_header Host {{.BackupHostHeader}};
		proxy_set_header X-Request-ID $request_id;
		{{if .DedicatedWebSocket}}proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		{{else}}proxy_set_header Upgrade $cdn_upstream_upgrade;
		proxy_set_header Connection $cdn_connection_upgrade;
		{{end}}
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		proxy_ssl_session_reuse on;
		{{end}}
	}

	{{if .DedicatedWebSocket}}
	location @cdn_websocket_backup_{{.ID}} {
		internal;
		proxy_http_version 1.1;
		{{if $.RateLimitEnabled}}header_filter_by_lua_block { package.loaded.simple_cdn_rate_limit.response() }
		{{end}}
		proxy_pass {{.PrimaryScheme}}://{{.BackupWebSocketUpstreamName}};
		proxy_set_header Host {{.BackupHostHeader}};
		proxy_set_header X-Request-ID $request_id;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection upgrade;
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if not .RequestBodyBuffering}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .UseTLS}}
		proxy_ssl_server_name on;
		proxy_ssl_name {{.BackupTLSName}};
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 3;
		proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		proxy_ssl_session_reuse on;
		{{end}}
	}
	{{end}}
	{{end}}
		{{end}}
}
# CDN HTTP site fragment {{.ID}} end
{{end}}
`

type renderedSite struct {
	ID                           string
	DomainList                   string
	HealthBody                   string
	PrimaryHostPort              string
	PrimaryTLSName               string
	PrimaryScheme                string
	PrimaryUpstreamName          string
	PrimaryWebSocketUpstreamName string
	PrimaryProxyHTTPVersion      string
	PrimaryUsesHTTP2             bool
	UseTLS                       bool
	BackupHostPort               string
	BackupTLSName                string
	BackupHostHeader             string
	BackupUpstreamName           string
	BackupWebSocketUpstreamName  string
	BackupProxyHTTPVersion       string
	BackupOriginHTTPVersion      domain.OriginHTTPVersion
	BackupUsesHTTP2              bool
	DedicatedWebSocket           bool
	HostHeader                   string
	CacheGeneration              int64
	GRPC                         bool
	Passthrough                  bool
	HTTP3Enabled                 bool
	ClientMaxBodySizeMB          int
	ClientKeepaliveTimeout       string
	ReadWriteTimeout             string
	CacheEnabled                 bool
	AlwaysUnbuffered             bool
	RequestBodyBuffering         bool
	OriginResponseBuffering      bool
	StaticAssets                 []renderedStaticAsset
}

type renderedStaticAsset struct {
	URLPath      string
	ObjectPath   string
	ContentType  string
	CacheControl string
}

type renderedOriginPool struct {
	Name                 string
	HTTP1AliasName       string
	ConfigPath           string
	KeepaliveConnections int
}

type originPoolBuilder struct {
	pool           domain.OriginPool
	name           string
	http1AliasName string
}

type renderedCachePath struct {
	Path     string
	Zone     string
	ZoneSize string
	MaxSize  string
}

type renderInput struct {
	Sites                         []renderedSite
	OriginPools                   []renderedOriginPool
	ManagedOriginPools            bool
	CachePaths                    []renderedCachePath
	DefaultHTTP                   bool
	HTTP3Enabled                  bool
	LegacySecurityEnabled         bool
	RuntimeSecurityEnabled        bool
	RuntimeSecurityLogs           []renderedWAFLog
	SecurityConfig                string
	RateLimitEnabled              bool
	RateLimitBanEnabled           bool
	RateLimitConfig               string
	DefaultClientKeepaliveTimeout string
	ClientKeepaliveRequests       int
	UpstreamConnectTimeout        string
	UpstreamKeepaliveConnections  int
	StaticAssetPathPattern        string
	QUICHostKeyPath               string
}

func Render(sites []domain.Site) (string, error) {
	return RenderWithSecurityAndRateLimit(sites, nil, nil)
}

func RenderWithSecurity(sites []domain.Site, securityPolicies []domain.SecurityPolicy) (string, error) {
	return RenderWithSecurityAndRateLimit(sites, securityPolicies, nil)
}

func RenderWithSecurityAndRateLimit(sites []domain.Site, securityPolicies []domain.SecurityPolicy, rateLimitPolicies []domain.RateLimitPolicy) (string, error) {
	return RenderWithOptions(sites, securityPolicies, rateLimitPolicies, domain.DefaultCacheMaxSizeGB)
}

func RenderWithOptions(sites []domain.Site, securityPolicies []domain.SecurityPolicy, rateLimitPolicies []domain.RateLimitPolicy, defaultCacheSizeGB int) (string, error) {
	return RenderWithRuntimeOptions(sites, securityPolicies, rateLimitPolicies, RenderRuntimeOptions{DefaultCacheSizeGB: defaultCacheSizeGB})
}

func RenderWithLegacyCache(sites []domain.Site, securityPolicies []domain.SecurityPolicy, rateLimitPolicies []domain.RateLimitPolicy, defaultCacheSizeGB int) (string, error) {
	return RenderWithRuntimeOptions(sites, securityPolicies, rateLimitPolicies, RenderRuntimeOptions{DefaultCacheSizeGB: defaultCacheSizeGB})
}

type RenderRuntimeOptions struct {
	DefaultCacheSizeGB        int
	HTTP3Capable              bool
	ManagedOriginPools        bool
	OriginHTTP2Capable        bool
	NginxWorkerConnections    int
	OriginPoolConfigDirectory string
	QUICHostKeyPath           string
	WAFChainCapable           bool
	POWCapable                bool
	POWPolicies               []domain.POWPolicyRuntime
	StaticAssets              []domain.StaticAssetReference
	StaticAssetDirectory      string
	originPoolsOutput         *[]domain.OriginPool
}

type RenderedNodeConfiguration struct {
	NginxConfig string
	OriginPools []domain.OriginPool
}

func RenderNodeWithRuntimeOptions(sites []domain.Site, securityPolicies []domain.SecurityPolicy, rateLimitPolicies []domain.RateLimitPolicy, options RenderRuntimeOptions) (RenderedNodeConfiguration, error) {
	var pools []domain.OriginPool
	options.originPoolsOutput = &pools
	configuration, err := RenderWithRuntimeOptions(sites, securityPolicies, rateLimitPolicies, options)
	if err != nil {
		return RenderedNodeConfiguration{}, err
	}
	return RenderedNodeConfiguration{NginxConfig: configuration, OriginPools: pools}, nil
}

func RenderWithRuntimeOptions(sites []domain.Site, securityPolicies []domain.SecurityPolicy, rateLimitPolicies []domain.RateLimitPolicy, options RenderRuntimeOptions) (string, error) {
	cacheSizeGB := options.DefaultCacheSizeGB
	if err := domain.ValidateCacheMaxSizeGB(cacheSizeGB); err != nil {
		return "", err
	}
	var err error
	if rateLimitPolicies != nil {
		rateLimitPolicies, err = normalizeRateLimitPolicies(rateLimitPolicies)
		if err != nil {
			return "", err
		}
	}
	items := make([]renderedSite, 0, len(sites))
	poolBuilders := make(map[string]*originPoolBuilder)
	poolDirectory := strings.TrimRight(strings.TrimSpace(options.OriginPoolConfigDirectory), "/")
	if poolDirectory == "" {
		poolDirectory = DefaultOriginPoolConfigDirectory
	}
	quicHostKeyPath := strings.TrimSpace(options.QUICHostKeyPath)
	if quicHostKeyPath == "" {
		quicHostKeyPath = DefaultQUICHostKeyPath
	}
	if !filepath.IsAbs(quicHostKeyPath) || filepath.Clean(quicHostKeyPath) != quicHostKeyPath {
		return "", fmt.Errorf("QUIC host key path must be an absolute clean path")
	}
	staticAssetDirectory := strings.TrimRight(strings.TrimSpace(options.StaticAssetDirectory), "/")
	if staticAssetDirectory == "" {
		staticAssetDirectory = DefaultStaticAssetDirectory
	}
	if !filepath.IsAbs(staticAssetDirectory) || filepath.Clean(staticAssetDirectory) != staticAssetDirectory ||
		strings.ContainsAny(staticAssetDirectory, "\x00\r\n\"$") {
		return "", fmt.Errorf("static asset directory must be a safe absolute clean path")
	}
	staticAssetsBySite := make(map[string][]renderedStaticAsset)
	staticAssetPaths := make(map[string]struct{})
	for _, reference := range options.StaticAssets {
		reference, err = domain.NormalizeStaticAssetReference(reference)
		if err != nil {
			return "", fmt.Errorf("static asset reference %q: %w", reference.BindingID, err)
		}
		key := reference.SiteID + "\x00" + reference.URLPath
		if _, found := staticAssetPaths[key]; found {
			return "", fmt.Errorf("site %s has duplicate static asset URL %s", reference.SiteID, reference.URLPath)
		}
		staticAssetPaths[key] = struct{}{}
		staticAssetsBySite[reference.SiteID] = append(staticAssetsBySite[reference.SiteID], renderedStaticAsset{
			URLPath: reference.URLPath, ObjectPath: staticAssetDirectory + "/" + reference.SHA256,
			ContentType: reference.ContentType, CacheControl: reference.CacheControl,
		})
	}
	for siteID := range staticAssetsBySite {
		sort.Slice(staticAssetsBySite[siteID], func(i, j int) bool {
			return staticAssetsBySite[siteID][i].URLPath < staticAssetsBySite[siteID][j].URLPath
		})
	}
	cachePaths := make([]renderedCachePath, 0, 1)
	cacheEnabled := false
	http3Enabled := false
	dedicatedTCP := false
	for _, site := range sites {
		if site.TCPOnly {
			dedicatedTCP = true
		}
		if !site.Enabled || site.TCPOnly {
			continue
		}
		clientMaxBodySizeMB, err := domain.NormalizeClientMaxBodySizeMB(site.ClientMaxBodySizeMB)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		readWriteTimeoutSeconds, err := domain.NormalizeReadWriteTimeoutSeconds(site.ReadWriteTimeoutSeconds)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		clientKeepaliveTimeoutSeconds, err := domain.NormalizeClientKeepaliveTimeoutSeconds(site.ClientKeepaliveTimeoutSeconds)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		primary, err := parseOrigin(site.PrimaryOrigin)
		if err != nil {
			return "", fmt.Errorf("site %s primary origin: %w", site.Name, err)
		}
		if site.Passthrough && primary.Scheme != "http" && primary.Scheme != "https" {
			return "", fmt.Errorf("site %s passthrough mode is only supported for HTTP and HTTPS origins", site.Name)
		}
		primaryHTTPVersion, err := renderOriginHTTPVersion(primary.Scheme, site.PrimaryOrigin.HTTPVersion)
		if err != nil {
			return "", fmt.Errorf("site %s primary origin: %w", site.Name, err)
		}
		if isHTTP2OriginVersion(primaryHTTPVersion) && !options.OriginHTTP2Capable {
			return "", fmt.Errorf("site %s requires an edge with HTTP/2 origin support", site.Name)
		}
		alwaysUnbuffered := site.Passthrough || domain.IsWebSocketScheme(primary.Scheme)
		item := renderedSite{
			ID: site.ID, DomainList: strings.Join(site.Domains, " "), HealthBody: SiteHealthBody(site.ID), PrimaryHostPort: primary.Host, PrimaryTLSName: site.PrimaryOrigin.TLSServerName,
			PrimaryScheme: domain.ProxyScheme(primary.Scheme), UseTLS: domain.OriginUsesTLS(primary.Scheme), HostHeader: site.PrimaryOrigin.HostHeader, CacheGeneration: site.CacheGeneration,
			GRPC: domain.IsGRPCScheme(primary.Scheme), Passthrough: site.Passthrough, HTTP3Enabled: options.HTTP3Capable && site.HTTP3Enabled, ClientMaxBodySizeMB: clientMaxBodySizeMB,
			ClientKeepaliveTimeout:  fmt.Sprintf("%ds", clientKeepaliveTimeoutSeconds),
			ReadWriteTimeout:        fmt.Sprintf("%ds", readWriteTimeoutSeconds),
			CacheEnabled:            primary.Scheme == "http" || primary.Scheme == "https",
			AlwaysUnbuffered:        alwaysUnbuffered,
			RequestBodyBuffering:    site.RequestBodyBuffering && !alwaysUnbuffered,
			OriginResponseBuffering: site.OriginResponseBuffering && !alwaysUnbuffered,
			PrimaryProxyHTTPVersion: nginxProxyHTTPVersion(primaryHTTPVersion),
			PrimaryUsesHTTP2:        isHTTP2OriginVersion(primaryHTTPVersion),
			StaticAssets:            staticAssetsBySite[site.ID],
		}
		delete(staticAssetsBySite, site.ID)
		http3Enabled = http3Enabled || item.HTTP3Enabled
		item.PrimaryUpstreamName = "origin_" + item.ID
		item.PrimaryWebSocketUpstreamName = item.PrimaryUpstreamName
		item.CacheEnabled = item.CacheEnabled && !site.Passthrough && item.OriginResponseBuffering
		if item.CacheEnabled {
			cacheEnabled = true
		}
		if item.HostHeader == "" {
			item.HostHeader = primary.Hostname()
		}
		if item.PrimaryTLSName == "" {
			item.PrimaryTLSName = primary.Hostname()
		}
		if site.BackupOrigin != nil && site.BackupOrigin.Enabled {
			backup, err := parseOrigin(*site.BackupOrigin)
			if err != nil {
				return "", fmt.Errorf("site %s backup origin: %w", site.Name, err)
			}
			if backup.Scheme != primary.Scheme {
				return "", fmt.Errorf("site %s origins must use the same scheme", site.Name)
			}
			item.BackupHostPort = backup.Host
			backupHTTPVersion, err := renderOriginHTTPVersion(backup.Scheme, site.BackupOrigin.HTTPVersion)
			if err != nil {
				return "", fmt.Errorf("site %s backup origin: %w", site.Name, err)
			}
			if isHTTP2OriginVersion(backupHTTPVersion) && !options.OriginHTTP2Capable {
				return "", fmt.Errorf("site %s requires an edge with HTTP/2 origin support", site.Name)
			}
			item.BackupProxyHTTPVersion = nginxProxyHTTPVersion(backupHTTPVersion)
			item.BackupOriginHTTPVersion = backupHTTPVersion
			item.BackupUsesHTTP2 = isHTTP2OriginVersion(backupHTTPVersion)
			item.BackupTLSName = site.BackupOrigin.TLSServerName
			item.BackupHostHeader = site.BackupOrigin.HostHeader
			if item.BackupHostHeader == "" {
				item.BackupHostHeader = backup.Hostname()
			}
			if item.BackupTLSName == "" {
				item.BackupTLSName = backup.Hostname()
			}
			item.PrimaryUpstreamName = "origin_" + item.ID + "_primary"
			item.BackupUpstreamName = "origin_" + item.ID + "_backup"
			item.PrimaryWebSocketUpstreamName = item.PrimaryUpstreamName
			item.BackupWebSocketUpstreamName = item.BackupUpstreamName
		}
		if item.PrimaryUsesHTTP2 {
			item.PrimaryWebSocketUpstreamName = item.PrimaryUpstreamName + "_http1"
		}
		if item.BackupUsesHTTP2 {
			item.BackupWebSocketUpstreamName = item.BackupUpstreamName + "_http1"
		}
		item.DedicatedWebSocket = item.PrimaryUsesHTTP2 || item.BackupUsesHTTP2
		if options.ManagedOriginPools {
			primaryPool, err := addOriginPool(poolBuilders, poolDirectory, item.PrimaryScheme, primaryHTTPVersion, item.PrimaryHostPort, item.HostHeader, tlsName(item.UseTLS, item.PrimaryTLSName), site.ID, "primary")
			if err != nil {
				return "", fmt.Errorf("site %s primary origin pool: %w", site.Name, err)
			}
			item.PrimaryUpstreamName = primaryPool.name
			item.PrimaryWebSocketUpstreamName = primaryPool.name
			if item.PrimaryUsesHTTP2 {
				item.PrimaryWebSocketUpstreamName = primaryPool.http1AliasName
			}
			if item.BackupHostPort != "" {
				backupPool, err := addOriginPool(poolBuilders, poolDirectory, item.PrimaryScheme, item.BackupOriginHTTPVersion, item.BackupHostPort, item.BackupHostHeader, tlsName(item.UseTLS, item.BackupTLSName), site.ID, "backup")
				if err != nil {
					return "", fmt.Errorf("site %s backup origin pool: %w", site.Name, err)
				}
				item.BackupUpstreamName = backupPool.name
				item.BackupWebSocketUpstreamName = backupPool.name
				if item.BackupUsesHTTP2 {
					item.BackupWebSocketUpstreamName = backupPool.http1AliasName
				}
			}
		}
		items = append(items, item)
	}
	if len(staticAssetsBySite) != 0 {
		return "", fmt.Errorf("static asset references include a site that is not enabled on this node")
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	originPools, renderedOriginPools, err := finalizeOriginPools(poolBuilders, options.NginxWorkerConnections)
	if err != nil {
		return "", err
	}
	if options.originPoolsOutput != nil {
		*options.originPoolsOutput = append([]domain.OriginPool(nil), originPools...)
	}
	if cacheEnabled {
		cachePaths = append(cachePaths, renderedCachePath{Path: DefaultCachePath, Zone: "cdn_cache", ZoneSize: cacheZoneSize(cacheSizeGB, len(cacheEnabledItems(items))), MaxSize: fmt.Sprintf("%dg", cacheSizeGB)})
	}
	template, err := template.New("nginx").Parse(configTemplate)
	if err != nil {
		return "", err
	}
	var out bytes.Buffer
	httpEnabled := len(items) > 0 || !dedicatedTCP
	legacySecurityEnabled := !options.WAFChainCapable && len(enabledLegacySecurityPolicies(securityPolicies)) > 0 && httpEnabled
	runtimeSecurityEnabled := options.WAFChainCapable &&
		(len(enabledSecurityPolicies(securityPolicies)) > 0 || len(enabledPOWPolicies(options.POWPolicies)) > 0) && httpEnabled
	securityConfig := renderSecurityConfig(securityPolicies, httpEnabled)
	var runtimeSecurityLogs []renderedWAFLog
	if options.WAFChainCapable {
		securityConfig, runtimeSecurityLogs, err = renderWAFConfig(securityPolicies, options.POWPolicies, httpEnabled, options.POWCapable)
		if err != nil {
			return "", err
		}
	}
	if err := template.Execute(&out, renderInput{
		Sites:                         items,
		OriginPools:                   renderedOriginPools,
		ManagedOriginPools:            options.ManagedOriginPools,
		CachePaths:                    cachePaths,
		DefaultHTTP:                   !dedicatedTCP,
		HTTP3Enabled:                  http3Enabled,
		LegacySecurityEnabled:         legacySecurityEnabled,
		RuntimeSecurityEnabled:        runtimeSecurityEnabled,
		RuntimeSecurityLogs:           runtimeSecurityLogs,
		SecurityConfig:                securityConfig,
		RateLimitEnabled:              len(enabledRateLimitPolicies(rateLimitPolicies)) > 0 && httpEnabled,
		RateLimitBanEnabled:           hasEnabledRateLimitBanPolicy(rateLimitPolicies) && httpEnabled,
		RateLimitConfig:               renderRateLimitConfig(rateLimitPolicies, httpEnabled),
		DefaultClientKeepaliveTimeout: fmt.Sprintf("%ds", domain.DefaultClientKeepaliveTimeoutSeconds),
		ClientKeepaliveRequests:       defaultClientKeepaliveRequests,
		UpstreamConnectTimeout:        defaultUpstreamConnectTimeout,
		UpstreamKeepaliveConnections:  defaultUpstreamKeepaliveConnections,
		StaticAssetPathPattern:        staticAssetPathPattern,
		QUICHostKeyPath:               quicHostKeyPath,
	}); err != nil {
		return "", err
	}
	return out.String(), nil
}

func addOriginPool(builders map[string]*originPoolBuilder, directory, scheme string, httpVersion domain.OriginHTTPVersion, address, hostHeader, serverName, siteID, role string) (*originPoolBuilder, error) {
	normalizedAddress, err := normalizeOriginPoolAddress(scheme, address)
	if err != nil {
		return nil, err
	}
	address = normalizedAddress
	hostHeader = strings.ToLower(hostHeader)
	serverName = strings.ToLower(serverName)
	keyParts := []string{scheme, address, hostHeader, serverName}
	if httpVersion != "" && httpVersion != domain.OriginHTTPVersionHTTP1 {
		keyParts = append(keyParts, string(httpVersion))
	}
	key := strings.Join(keyParts, "\x00")
	if existing := builders[key]; existing != nil {
		existing.pool.References = append(existing.pool.References, domain.OriginPoolReference{SiteID: siteID, Role: role})
		return existing, nil
	}
	digest := sha256.Sum256([]byte(key))
	id := fmt.Sprintf("%x", digest[:12])
	builder := &originPoolBuilder{
		name: "origin_pool_" + id, http1AliasName: "origin_pool_" + id + "_http1",
		pool: domain.OriginPool{
			ID: id, Address: address, Scheme: scheme, HTTPVersion: httpVersion, HostHeader: hostHeader, TLSServerName: serverName,
			ConfigPath: directory + "/" + id + ".conf",
			References: []domain.OriginPoolReference{{SiteID: siteID, Role: role}},
		},
	}
	builders[key] = builder
	return builder, nil
}

func renderOriginHTTPVersion(scheme string, version domain.OriginHTTPVersion) (domain.OriginHTTPVersion, error) {
	if domain.IsGRPCScheme(scheme) {
		if version != "" {
			return "", fmt.Errorf("HTTP version is managed by the gRPC upstream")
		}
		return "", nil
	}
	if version == "" {
		version = domain.OriginHTTPVersionHTTP1
	}
	switch scheme {
	case "ws", "wss":
		if version != domain.OriginHTTPVersionHTTP1 {
			return "", fmt.Errorf("WebSocket origins require HTTP/1.1")
		}
	case "http":
		if version != domain.OriginHTTPVersionHTTP1 && version != domain.OriginHTTPVersionH2C {
			return "", fmt.Errorf("HTTP origins support only HTTP/1.1 or H2C")
		}
	case "https":
		if version != domain.OriginHTTPVersionHTTP1 && version != domain.OriginHTTPVersionHTTP2 {
			return "", fmt.Errorf("HTTPS origins support only HTTP/1.1 or HTTP/2")
		}
	default:
		return "", fmt.Errorf("unsupported origin scheme %q", scheme)
	}
	return version, nil
}

func nginxProxyHTTPVersion(version domain.OriginHTTPVersion) string {
	if isHTTP2OriginVersion(version) {
		return "2"
	}
	return "1.1"
}

func isHTTP2OriginVersion(version domain.OriginHTTPVersion) bool {
	return version == domain.OriginHTTPVersionHTTP2 || version == domain.OriginHTTPVersionH2C
}

func normalizeOriginPoolAddress(scheme, address string) (string, error) {
	parsed, err := url.Parse(scheme + "://" + address)
	if err != nil || parsed.Host == "" || parsed.User != nil || parsed.Path != "" || parsed.RawQuery != "" || parsed.Fragment != "" {
		return "", fmt.Errorf("invalid origin address %q", address)
	}
	host := parsed.Hostname()
	port := parsed.Port()
	if port == "" {
		switch scheme {
		case "http", "grpc":
			port = "80"
		case "https", "grpcs":
			port = "443"
		default:
			return "", fmt.Errorf("unsupported origin scheme %q", scheme)
		}
	}
	normalized, err := domain.NormalizeMonitoringAddress(net.JoinHostPort(host, port))
	if err != nil {
		return "", err
	}
	return normalized, nil
}

func tlsName(enabled bool, value string) string {
	if !enabled {
		return ""
	}
	return value
}

func finalizeOriginPools(builders map[string]*originPoolBuilder, workerConnections int) ([]domain.OriginPool, []renderedOriginPool, error) {
	if len(builders) > domain.MaxOriginPools {
		return nil, nil, fmt.Errorf("node has %d origin connection pools; maximum is %d", len(builders), domain.MaxOriginPools)
	}
	ordered := make([]*originPoolBuilder, 0, len(builders))
	for _, builder := range builders {
		sort.Slice(builder.pool.References, func(i, j int) bool {
			if builder.pool.References[i].SiteID != builder.pool.References[j].SiteID {
				return builder.pool.References[i].SiteID < builder.pool.References[j].SiteID
			}
			return builder.pool.References[i].Role < builder.pool.References[j].Role
		})
		ordered = append(ordered, builder)
	}
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].pool.ID < ordered[j].pool.ID })
	if len(ordered) == 0 {
		return nil, nil, nil
	}
	if workerConnections <= 0 {
		workerConnections = domain.DefaultNginxWorkerConnections
	}
	budget := workerConnections / 16
	if budget < 16 {
		budget = 16
	}
	if budget > 1024 {
		budget = 1024
	}
	if budget < len(ordered) {
		budget = len(ordered)
	}
	maximum := 64
	if workerConnections >= 16384 {
		maximum = 128
	}
	if budget > len(ordered)*maximum {
		budget = len(ordered) * maximum
	}
	sizes := make([]int, len(ordered))
	for index := range sizes {
		sizes[index] = 1
	}
	for remaining := budget - len(ordered); remaining > 0; remaining-- {
		selected := -1
		selectedRatio := 0.0
		for index, builder := range ordered {
			if sizes[index] >= maximum {
				continue
			}
			ratio := float64(sizes[index]) / float64(len(builder.pool.References))
			if selected == -1 || ratio < selectedRatio {
				selected = index
				selectedRatio = ratio
			}
		}
		if selected == -1 {
			break
		}
		sizes[selected]++
	}
	pools := make([]domain.OriginPool, 0, len(ordered))
	rendered := make([]renderedOriginPool, 0, len(ordered))
	for index, builder := range ordered {
		builder.pool.KeepaliveConnections = sizes[index]
		if !domain.ValidOriginPool(builder.pool) {
			return nil, nil, fmt.Errorf("rendered origin pool %s is invalid", builder.pool.ID)
		}
		pools = append(pools, builder.pool)
		rendered = append(rendered, renderedOriginPool{
			Name: builder.name, ConfigPath: builder.pool.ConfigPath, KeepaliveConnections: builder.pool.KeepaliveConnections,
			HTTP1AliasName: func() string {
				if builder.pool.HTTPVersion == domain.OriginHTTPVersionHTTP2 || builder.pool.HTTPVersion == domain.OriginHTTPVersionH2C {
					return builder.http1AliasName
				}
				return ""
			}(),
		})
	}
	return pools, rendered, nil
}

func cacheEnabledItems(items []renderedSite) []renderedSite {
	result := make([]renderedSite, 0, len(items))
	for _, item := range items {
		if item.CacheEnabled {
			result = append(result, item)
		}
	}
	return result
}

func cacheZoneSize(cacheSizeGB, cacheSiteCount int) string {
	const (
		minZoneSizeMB = 16
		maxZoneSizeMB = 512
	)
	// Cache metadata needs to grow with both the object budget and the number
	// of independently assigned sites, while staying within a bounded RAM use.
	zoneSizeMB := cacheSizeGB*8 + cacheSiteCount*4
	if zoneSizeMB < minZoneSizeMB {
		zoneSizeMB = minZoneSizeMB
	}
	if zoneSizeMB > maxZoneSizeMB {
		zoneSizeMB = maxZoneSizeMB
	}
	return fmt.Sprintf("%dm", zoneSizeMB)
}

func RenderCapacity(capacity domain.NginxCapacity) (string, string, error) {
	capacity, err := domain.NormalizeNginxCapacity(capacity)
	if err != nil {
		return "", "", err
	}
	workerProcesses := "auto"
	if capacity.WorkerProcesses > 0 {
		workerProcesses = fmt.Sprintf("%d", capacity.WorkerProcesses)
	}
	return fmt.Sprintf("# Generated by cdn-edge-agent. Do not edit.\npcre_jit on;\nworker_processes %s;\nworker_rlimit_nofile %d;\nworker_shutdown_timeout 1h;\n", workerProcesses, capacity.WorkerRlimitNoFile),
		fmt.Sprintf("# Generated by cdn-edge-agent. Do not edit.\nworker_connections %d;\n", capacity.WorkerConnections), nil
}

func SplitHTTPConfig(configuration string) (string, []domain.NginxConfigFragment, error) {
	const markerPrefix = "# CDN HTTP site fragment "
	var base strings.Builder
	fragments := make([]domain.NginxConfigFragment, 0)
	cursor := 0
	for {
		relativeStart := strings.Index(configuration[cursor:], markerPrefix)
		if relativeStart < 0 {
			base.WriteString(configuration[cursor:])
			break
		}
		start := cursor + relativeStart
		lineEnd := strings.IndexByte(configuration[start:], '\n')
		if lineEnd < 0 {
			return "", nil, errors.New("HTTP site fragment marker is incomplete")
		}
		lineEnd += start
		marker := strings.TrimSpace(configuration[start:lineEnd])
		if !strings.HasSuffix(marker, " begin") {
			return "", nil, fmt.Errorf("invalid HTTP site fragment marker %q", marker)
		}
		siteID := strings.TrimSuffix(strings.TrimPrefix(marker, markerPrefix), " begin")
		if siteID == "" {
			return "", nil, errors.New("HTTP site fragment marker is missing a site ID")
		}
		endMarker := markerPrefix + siteID + " end"
		relativeEnd := strings.Index(configuration[lineEnd+1:], endMarker)
		if relativeEnd < 0 {
			return "", nil, fmt.Errorf("HTTP site fragment %s has no end marker", siteID)
		}
		end := lineEnd + 1 + relativeEnd + len(endMarker)
		if end < len(configuration) && configuration[end] == '\n' {
			end++
		}
		base.WriteString(configuration[cursor:start])
		fragments = append(fragments, domain.NginxConfigFragment{Name: siteFragmentName(siteID), Content: configuration[start:end]})
		cursor = end
	}
	return base.String(), fragments, nil
}

func SplitConfigFragments(httpConfiguration, streamConfiguration string) (*domain.NginxConfigFragments, error) {
	httpBase, httpSites, err := SplitHTTPConfig(httpConfiguration)
	if err != nil {
		return nil, err
	}
	streamBase, streamSites, err := SplitStreamConfig(streamConfiguration)
	if err != nil {
		return nil, err
	}
	return &domain.NginxConfigFragments{
		HTTPBase: httpBase, HTTPSites: httpSites, StreamBase: streamBase, StreamSites: streamSites,
	}, nil
}

func siteFragmentName(siteID string) string {
	var name strings.Builder
	for _, character := range siteID {
		if character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z' ||
			character >= '0' && character <= '9' || character == '-' || character == '_' || character == '.' {
			name.WriteRune(character)
			continue
		}
		name.WriteByte('-')
	}
	return "site-" + name.String() + ".conf"
}

func normalizeRateLimitPolicies(policies []domain.RateLimitPolicy) ([]domain.RateLimitPolicy, error) {
	result := make([]domain.RateLimitPolicy, 0, len(policies))
	for _, policy := range policies {
		normalized, err := domain.NormalizeRateLimitPolicy(policy)
		if err != nil {
			return nil, fmt.Errorf("rate limit policy %q: %w", policy.Name, err)
		}
		result = append(result, normalized)
	}
	return result, nil
}

func enabledRateLimitPolicies(policies []domain.RateLimitPolicy) []domain.RateLimitPolicy {
	result := make([]domain.RateLimitPolicy, 0, len(policies))
	for _, policy := range policies {
		if policy.Enabled {
			result = append(result, policy)
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result
}

func hasEnabledRateLimitBanPolicy(policies []domain.RateLimitPolicy) bool {
	for _, policy := range policies {
		if policy.Enabled && policy.BanEnabled {
			return true
		}
	}
	return false
}

func enabledSecurityPolicies(policies []domain.SecurityPolicy) []domain.SecurityPolicy {
	result := make([]domain.SecurityPolicy, 0, len(policies))
	for _, policy := range policies {
		if policy.Enabled {
			result = append(result, policy)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].Priority != result[j].Priority {
			return result[i].Priority < result[j].Priority
		}
		return result[i].ID < result[j].ID
	})
	return result
}

func enabledLegacySecurityPolicies(policies []domain.SecurityPolicy) []domain.SecurityPolicy {
	result := make([]domain.SecurityPolicy, 0, len(policies))
	for _, policy := range policies {
		if !policy.Enabled {
			continue
		}
		legacy, ok := domain.LegacySecurityPolicy(policy)
		if ok {
			result = append(result, legacy)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].Priority != result[j].Priority {
			return result[i].Priority < result[j].Priority
		}
		return result[i].ID < result[j].ID
	})
	return result
}

func renderSecurityConfig(policies []domain.SecurityPolicy, httpEnabled bool) string {
	if policies == nil {
		return ""
	}
	var result strings.Builder
	result.WriteString(SecurityRevisionMarker(policies))
	result.WriteByte('\n')
	policies = enabledLegacySecurityPolicies(policies)
	if len(policies) == 0 || !httpEnabled {
		return result.String()
	}
	result.WriteString("map $uri $cdn_security_policy_id {\n    default \"\";\n")
	for _, policy := range policies {
		result.WriteString("    \"~")
		result.WriteString(escapeNginxQuotedPattern(policy.Pattern))
		result.WriteString("\" \"")
		result.WriteString(policy.ID)
		result.WriteString("\";\n")
	}
	result.WriteString("}\n\nmap $cdn_security_policy_id $cdn_security_action {\n    default \"\";\n")
	for _, policy := range policies {
		result.WriteString(fmt.Sprintf("    \"%s\" \"%s\";\n", policy.ID, policy.Action))
	}
	result.WriteString("}\n\nmap $cdn_security_policy_id $cdn_security_ban_seconds {\n    default 0;\n")
	for _, policy := range policies {
		result.WriteString(fmt.Sprintf("    \"%s\" %d;\n", policy.ID, policy.BanDurationSeconds))
	}
	result.WriteString("}\n\nlog_format cdn_security_json escape=json '{\"timestamp\":\"$time_iso8601\",\"policy_id\":\"$cdn_security_policy_id\",\"action\":\"$cdn_security_action\",\"ban_seconds\":$cdn_security_ban_seconds,\"client_ip\":\"$remote_addr\",\"host\":\"$host\",\"method\":\"$request_method\",\"path\":\"$uri\"}';\n")
	return result.String()
}

func renderRateLimitConfig(policies []domain.RateLimitPolicy, httpEnabled bool) string {
	if policies == nil {
		return ""
	}
	var result strings.Builder
	result.WriteString(RateLimitRevisionMarker(policies))
	result.WriteByte('\n')
	policies = enabledRateLimitPolicies(policies)
	if len(policies) == 0 || !httpEnabled {
		return result.String()
	}
	result.WriteString("lua_shared_dict cdn_rate_limit 20m;\n")
	if hasEnabledRateLimitBanPolicy(policies) {
		result.WriteString(`lua_shared_dict cdn_rate_limit_escalation 10m;
map $request_id $cdn_rate_limit_ban_policy_id { default ""; }
map $request_id $cdn_rate_limit_ban_seconds { default 0; }
log_format cdn_rate_limit_ban_json escape=json '{"timestamp":"$time_iso8601","policy_id":"$cdn_rate_limit_ban_policy_id","action":"ban","ban_seconds":$cdn_rate_limit_ban_seconds,"client_ip":"$remote_addr","host":"$host","method":"$request_method","path":"$uri"}';
`)
	}
	result.WriteString(`init_by_lua_block {
    local policies = {
`)
	for _, policy := range policies {
		encodedID, _ := json.Marshal(policy.ID)
		result.WriteString("        { id = ")
		result.Write(encodedID)
		result.WriteString(fmt.Sprintf(", limit = %d", policy.RequestsPerSecond))
		if policy.ResponseConditionEnabled {
			result.WriteString(", statuses = { ")
			for index, class := range policy.ResponseStatusClasses {
				if index > 0 {
					result.WriteString(", ")
				}
				result.WriteString(fmt.Sprintf("[%d] = true", class))
			}
			result.WriteString(" }")
		}
		if policy.BanEnabled {
			result.WriteString(fmt.Sprintf(", ban_after = %d, ban_seconds = %d",
				policy.BanAfterConsecutive429, policy.BanDurationSeconds))
		}
		result.WriteString(" },\n")
	}
	result.WriteString(`    }
    local key_ttl = 3

    local function bucket_key(policy, client_ip, second)
        return policy.id .. ":" .. client_ip .. ":" .. second
    end

    local function window_rate(dict, policy, client_ip, now, increment)
        local second = math.floor(now)
        local current_key = bucket_key(policy, client_ip, second)
        local current
        if increment then
            current = dict:incr(current_key, 1, 0, key_ttl)
            if current == nil then
                return nil
            end
        else
            current = dict:get(current_key) or 0
        end
        local previous = dict:get(bucket_key(policy, client_ip, second - 1)) or 0
        return current + previous * (1 - (now - second))
    end

    local function escalation_key(kind, policy, client_ip)
        return kind .. ":" .. policy.id .. ":" .. client_ip
    end

    local function reset_rejection_streak(policy, client_ip)
        if policy.ban_after == nil then
            return
        end
        ngx.shared.cdn_rate_limit_escalation:delete(escalation_key("streak", policy, client_ip))
    end

    local function record_rejection(policy, client_ip)
        if policy.ban_after == nil then
            return
        end
        local escalation = ngx.shared.cdn_rate_limit_escalation
        local event_key = escalation_key("event", policy, client_ip)
        if escalation:get(event_key) then
            return
        end
        local streak_key = escalation_key("streak", policy, client_ip)
        local strikes = escalation:incr(streak_key, 1, 0, key_ttl)
        if strikes == nil then
            return
        end
        escalation:expire(streak_key, key_ttl)
        if strikes < policy.ban_after then
            return
        end
        local recorded = escalation:add(event_key, true, policy.ban_seconds)
        escalation:delete(streak_key)
        if not recorded then
            return
        end
        ngx.var.cdn_rate_limit_ban_policy_id = policy.id
        ngx.var.cdn_rate_limit_ban_seconds = tostring(policy.ban_seconds)
    end

    local function reject(policy, client_ip)
        ngx.ctx.cdn_rate_limit_rejected = true
        record_rejection(policy, client_ip)
        ngx.header["Retry-After"] = "1"
        ngx.header["Cache-Control"] = "no-store"
        return ngx.exit(429)
    end

    local function access()
		local security = package.loaded.simple_cdn_security
		if security ~= nil and security.access() then
			return
		end
        if ngx.is_subrequest then
            return
        end
        local client_ip = ngx.var.remote_addr
        if client_ip == nil or client_ip == "" then
            return
        end
        local dict = ngx.shared.cdn_rate_limit
        local now = ngx.now()
        for _, policy in ipairs(policies) do
            local count_requests = policy.statuses == nil
            local rate = window_rate(dict, policy, client_ip, now, count_requests)
            if rate ~= nil and ((count_requests and rate > policy.limit) or
                (not count_requests and rate >= policy.limit)) then
                return reject(policy, client_ip)
            end
            if rate ~= nil then
                reset_rejection_streak(policy, client_ip)
            end
        end
    end

    local function response()
        if ngx.is_subrequest or ngx.ctx.cdn_rate_limit_rejected then
            return
        end
        local client_ip = ngx.var.remote_addr
        if client_ip == nil or client_ip == "" then
            return
        end
        local status_class = math.floor((tonumber(ngx.status) or 0) / 100)
        local dict = ngx.shared.cdn_rate_limit
        local second = math.floor(ngx.now())
        for _, policy in ipairs(policies) do
            if policy.statuses ~= nil and policy.statuses[status_class] then
                dict:incr(bucket_key(policy, client_ip, second), 1, 0, key_ttl)
            end
        end
    end

    package.loaded.simple_cdn_rate_limit = { access = access, response = response }
}
`)
	return result.String()
}

func SecurityRevisionMarker(policies []domain.SecurityPolicy) string {
	type revisionPolicy struct {
		ID                 string
		Name               string
		Enabled            bool
		SiteIDs            []string
		Conditions         []domain.SecurityCondition
		Pattern            string
		Action             domain.SecurityPolicyAction
		BanDurationSeconds int
		ResponseStatus     int
		Priority           int
	}
	ordered := append([]domain.SecurityPolicy(nil), policies...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].ID < ordered[j].ID })
	revision := make([]revisionPolicy, 0, len(ordered))
	for _, policy := range ordered {
		if normalized, err := domain.NormalizeSecurityPolicy(policy); err == nil {
			normalized.ID = policy.ID
			normalized.Enabled = policy.Enabled
			policy = normalized
		}
		revision = append(revision, revisionPolicy{
			ID: policy.ID, Name: policy.Name, Enabled: policy.Enabled,
			SiteIDs: append([]string(nil), policy.SiteIDs...), Conditions: append([]domain.SecurityCondition(nil), policy.Conditions...),
			Pattern: policy.Pattern, Action: policy.Action, BanDurationSeconds: policy.BanDurationSeconds,
			ResponseStatus: policy.ResponseStatus, Priority: policy.Priority,
		})
	}
	encoded, _ := json.Marshal(revision)
	digest := sha256.Sum256(encoded)
	return fmt.Sprintf("# CDN security revision: %x", digest[:])
}

func HasSecurityRevision(configuration string, policies []domain.SecurityPolicy) bool {
	return strings.Contains(configuration, SecurityRevisionMarker(policies))
}

func RateLimitRevisionMarker(policies []domain.RateLimitPolicy) string {
	type revisionPolicy struct {
		ID                       string
		Name                     string
		Enabled                  bool
		Key                      string
		RequestsPerSecond        int
		ResponseConditionEnabled bool
		ResponseStatusClasses    []int
		BanEnabled               bool
		BanAfterConsecutive429   int
		BanDurationSeconds       int
	}
	ordered := append([]domain.RateLimitPolicy(nil), policies...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].ID < ordered[j].ID })
	revision := make([]revisionPolicy, 0, len(ordered))
	for _, policy := range ordered {
		if normalized, err := domain.NormalizeRateLimitPolicy(policy); err == nil {
			policy = normalized
		}
		revision = append(revision, revisionPolicy{
			ID: policy.ID, Name: policy.Name, Enabled: policy.Enabled, Key: domain.RateLimitKeyClientIP,
			RequestsPerSecond:        policy.RequestsPerSecond,
			ResponseConditionEnabled: policy.ResponseConditionEnabled,
			ResponseStatusClasses:    append([]int(nil), policy.ResponseStatusClasses...),
			BanEnabled:               policy.BanEnabled,
			BanAfterConsecutive429:   policy.BanAfterConsecutive429,
			BanDurationSeconds:       policy.BanDurationSeconds,
		})
	}
	encoded, _ := json.Marshal(revision)
	digest := sha256.Sum256(encoded)
	return fmt.Sprintf("# CDN rate limit revision: %x", digest[:])
}

func HasRateLimitRevision(configuration string, policies []domain.RateLimitPolicy) bool {
	return strings.Contains(configuration, RateLimitRevisionMarker(policies))
}

func escapeNginxQuotedPattern(pattern string) string {
	pattern = strings.ReplaceAll(pattern, `\`, `\\`)
	return strings.ReplaceAll(pattern, `"`, `\"`)
}

func SiteHealthBody(siteID string) string {
	return "site=" + siteID
}

func HasSiteHealth(configuration, siteID string) bool {
	return strings.Contains(configuration, `return 200 "`+SiteHealthBody(siteID)+`\n";`)
}

func HasRequestTracing(configuration string) bool {
	return strings.Contains(configuration, requestTracingMarker)
}

func parseOrigin(origin domain.Origin) (*url.URL, error) {
	parsed, err := url.Parse(origin.URL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return nil, fmt.Errorf("must be an absolute URL")
	}
	if !domain.ValidOriginScheme(parsed.Scheme) {
		return nil, fmt.Errorf("scheme must be http, https, ws, wss, grpc, or grpcs")
	}
	if parsed.Path != "" && parsed.Path != "/" {
		return nil, fmt.Errorf("origin URL cannot include a path")
	}
	if parsed.Port() == "" {
		if domain.OriginUsesTLS(parsed.Scheme) {
			parsed.Host += ":443"
		} else {
			parsed.Host += ":80"
		}
	}
	return parsed, nil
}
