package nginx

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"simple_cdn/internal/domain"
)

const (
	emptyStreamConfig       = "# Generated by cdn-edge-agent. Do not edit.\n"
	defaultTCPAccessLogPath = "/opt/cdn-edge/logs/tcp-access.json"
	defaultTCPErrorLogPath  = "/opt/cdn-edge/logs/tcp-error.log"
)

type renderedTCPForward struct {
	SiteID                string
	ListenPort            int
	ListenTLS             bool
	IPv6Enabled           bool
	UpstreamAddress       string
	UpstreamTLS           bool
	UpstreamTLSServerName string
	ConnectTimeoutSeconds int
	IdleTimeoutSeconds    int
}

func RenderStream(sites []domain.Site) (string, error) {
	items := make([]renderedTCPForward, 0)
	portOwners := make(map[int]string)
	hasHTTP, hasTCPOnly := false, false
	for _, site := range sites {
		if site.TCPOnly {
			hasTCPOnly = true
		} else {
			hasHTTP = true
		}
		if !site.Enabled {
			continue
		}
		for _, forward := range site.TCPForwards {
			if owner, found := portOwners[forward.ListenPort]; found {
				return "", fmt.Errorf("TCP listen port %d is assigned to both %s and %s", forward.ListenPort, owner, site.Name)
			}
			portOwners[forward.ListenPort] = site.Name
			connectTimeout := forward.ConnectTimeoutSeconds
			if connectTimeout == 0 {
				connectTimeout = domain.DefaultTCPConnectTimeoutSeconds
			}
			idleTimeout := forward.IdleTimeoutSeconds
			if idleTimeout == 0 {
				idleTimeout = domain.DefaultTCPIdleTimeoutSeconds
			}
			items = append(items, renderedTCPForward{
				SiteID: site.ID, ListenPort: forward.ListenPort, ListenTLS: forward.ListenTLS, IPv6Enabled: site.IPv6Enabled,
				UpstreamAddress: net.JoinHostPort(forward.UpstreamHost, fmt.Sprintf("%d", forward.UpstreamPort)),
				UpstreamTLS:     forward.UpstreamTLS, UpstreamTLSServerName: forward.UpstreamTLSServerName,
				ConnectTimeoutSeconds: connectTimeout, IdleTimeoutSeconds: idleTimeout,
			})
		}
	}
	if hasHTTP && hasTCPOnly {
		return "", fmt.Errorf("TCP-only and HTTP sites cannot share the same node")
	}
	if len(items) == 0 {
		return emptyStreamConfig, nil
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ListenPort < items[j].ListenPort })

	var out strings.Builder
	out.WriteString(emptyStreamConfig)
	out.WriteString("log_format cdn_tcp_json escape=json '{\"timestamp\":\"$time_iso8601\",\"site_id\":\"$cdn_tcp_site_id\",\"client_ip\":\"$remote_addr\",\"protocol\":\"$protocol\",\"status\":$status,\"bytes_sent\":$bytes_sent,\"bytes_received\":$bytes_received,\"duration_seconds\":$session_time,\"upstream\":\"$upstream_addr\",\"upstream_connect_seconds\":\"$upstream_connect_time\"}';\n\n")
	out.WriteString("map $server_port $cdn_tcp_site_id {\n    default \"\";\n")
	for _, item := range items {
		fmt.Fprintf(&out, "    %d \"%s\";\n", item.ListenPort, item.SiteID)
	}
	out.WriteString("}\n\nmap $server_port $cdn_tcp_upstream {\n    default \"\";\n")
	for _, item := range items {
		fmt.Fprintf(&out, "    %d \"%s\";\n", item.ListenPort, item.UpstreamAddress)
	}
	out.WriteString("}\n\nmap $server_port $cdn_tcp_upstream_sni {\n    default \"\";\n")
	for _, item := range items {
		fmt.Fprintf(&out, "    %d \"%s\";\n", item.ListenPort, item.UpstreamTLSServerName)
	}
	out.WriteString("}\n")

	for _, item := range items {
		fmt.Fprintf(&out, "\n# CDN stream site fragment %s port %d begin\n", item.SiteID, item.ListenPort)
		out.WriteString("server {\n")
		fmt.Fprintf(&out, "    listen %d", item.ListenPort)
		if item.ListenTLS {
			out.WriteString(" ssl")
		}
		out.WriteString(";\n\n")
		if item.IPv6Enabled {
			fmt.Fprintf(&out, "    listen [::]:%d ipv6only=on", item.ListenPort)
			if item.ListenTLS {
				out.WriteString(" ssl")
			}
			out.WriteString(";\n\n")
		}
		out.WriteString("    resolver 1.1.1.1 8.8.8.8 valid=1h ipv6=off;\n    resolver_timeout 5s;\n\n")
		out.WriteString("    proxy_pass $cdn_tcp_upstream;\n")
		fmt.Fprintf(&out, "    proxy_connect_timeout %ds;\n    proxy_timeout %ds;\n", item.ConnectTimeoutSeconds, item.IdleTimeoutSeconds)
		out.WriteString("    proxy_socket_keepalive on;\n")
		if item.ListenTLS {
			fmt.Fprintf(&out, "\n    ssl_certificate /opt/cdn-edge/config/certs/%s.crt;\n    ssl_certificate_key /opt/cdn-edge/config/certs/%s.key;\n", item.SiteID, item.SiteID)
			out.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_session_cache shared:TCPStreamSSL:20m;\n    ssl_session_timeout 10m;\n    ssl_session_tickets off;\n")
		}
		if item.UpstreamTLS {
			out.WriteString("\n    proxy_ssl on;\n    proxy_ssl_server_name on;\n    proxy_ssl_name $cdn_tcp_upstream_sni;\n    proxy_ssl_protocols TLSv1.2 TLSv1.3;\n    proxy_ssl_verify on;\n    proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;\n    proxy_ssl_verify_depth 3;\n")
		}
		fmt.Fprintf(&out, "\n    access_log %s cdn_tcp_json;\n    error_log %s warn;\n}\n", defaultTCPAccessLogPath, defaultTCPErrorLogPath)
		fmt.Fprintf(&out, "# CDN stream site fragment %s port %d end\n", item.SiteID, item.ListenPort)
	}
	return out.String(), nil
}

func SplitStreamConfig(configuration string) (string, []domain.NginxConfigFragment, error) {
	const markerPrefix = "# CDN stream site fragment "
	var base strings.Builder
	grouped := make(map[string]*strings.Builder)
	cursor := 0
	for {
		relativeStart := strings.Index(configuration[cursor:], markerPrefix)
		if relativeStart < 0 {
			base.WriteString(configuration[cursor:])
			break
		}
		start := cursor + relativeStart
		lineEnd := strings.IndexByte(configuration[start:], '\n')
		if lineEnd < 0 {
			return "", nil, fmt.Errorf("stream site fragment marker is incomplete")
		}
		lineEnd += start
		marker := strings.TrimSpace(configuration[start:lineEnd])
		fields := strings.Fields(marker)
		if len(fields) != 9 || fields[0] != "#" || fields[1] != "CDN" || fields[2] != "stream" ||
			fields[3] != "site" || fields[4] != "fragment" || fields[6] != "port" || fields[8] != "begin" {
			return "", nil, fmt.Errorf("invalid stream site fragment marker %q", marker)
		}
		siteID, port := fields[5], fields[7]
		endMarker := markerPrefix + siteID + " port " + port + " end"
		relativeEnd := strings.Index(configuration[lineEnd+1:], endMarker)
		if relativeEnd < 0 {
			return "", nil, fmt.Errorf("stream site fragment %s port %s has no end marker", siteID, port)
		}
		end := lineEnd + 1 + relativeEnd + len(endMarker)
		if end < len(configuration) && configuration[end] == '\n' {
			end++
		}
		base.WriteString(configuration[cursor:start])
		name := siteFragmentName(siteID)
		builder := grouped[name]
		if builder == nil {
			builder = &strings.Builder{}
			grouped[name] = builder
		}
		builder.WriteString(configuration[start:end])
		cursor = end
	}
	fragments := make([]domain.NginxConfigFragment, 0, len(grouped))
	for name, content := range grouped {
		fragments = append(fragments, domain.NginxConfigFragment{Name: name, Content: content.String()})
	}
	sort.Slice(fragments, func(i, j int) bool { return fragments[i].Name < fragments[j].Name })
	return base.String(), fragments, nil
}
